### ISSUE TITLE
Reset Password Functionality 

### ISSUE THREAD

**Issue by AlexMachin1997** [lucasweng/yelp-camp#1]
When i went to reset my password i got application error. This suggested you either don't have the environment variables on heroku setup or dont match. If the environment variables are correct check your google account settings as you will need to allow less secure apps and disable the invisible recaptcha 

less secure apps - https://myaccount.google.com/lesssecureapps

invisible recaptcha - https://accounts.google.com/b/0/DisplayUnlockCaptcha

Also how did you make the flash messages fade away ?

**Comment by lucasweng** [comment]
Hi Alex,
I disallowed the less secure apps a few weeks ago for I received an alert saying someone had tried to access that email account. I've made the functionality available again.

It seems like the flash messages will not fade away unless the page re-renders. I didn't manage to make that UX improvement.

Thanks for letting me know this issue and also for taking a look at the site! cheers

**Comment by AlexMachin1997** [comment]
Hey Lucaswng,

not a problem at all. I too was a bit sceptical about allowing less secure apps, it was showing someone else access my account but they werent it was just where the server was located i think. But you could try using Mailgun instead of nodemailer, ian one of the TAs of colts course did this (https://www.youtube.com/watch?v=3bxjvequldY&t=570s) which you could use.


As for the flash messages i added this:
  ```
  setTimeout(function(){
       $("#flash-message").addClass("bounceOut");
       $("#flash-message").delay(1000).hide('slow');
   }, 4500);
```

**Comment by lucasweng** [comment]
Understood and thanks for the info! I'll try using Mailgun if I'm to work on another project. I would try using vanilla javascript to save some load time like:

```
setTimeout(( ) => {
    const flashMessage = document.getElementById('flash-message');
    flashMessage.classList.add('bounceOut');
}, 4500)
```

Then handle delay and hide using CSS transitions
