### ISSUE TITLE
geocoder doesn't handle data with no location  

### ISSUE THREAD

**Issue by Ukuno** [lucasweng/yelp-camp#2]
I have been looking for a solution for this and the correct way to solve is to handle your data.status.
 if (err || data.status === 'ZERO_RESULTS') {
      req.flash('error', 'Invalid address, try typing a new address');
      return res.redirect('back');
    }
data.status needs to be 'OK' to proceed the next task.

**Comment by lucasweng** [comment]
Thanks for sharing that solution!
